### ISSUE TITLE
getting some cv2 related error

### ISSUE THREAD

**Issue by pavankay** [cvlab-columbia/zero123#116]
error: 
(zero123) C:\transformers\stable-zero123\zero123-main\zero123>python gradio_new.py
Traceback (most recent call last):
  File "C:\transformers\stable-zero123\zero123-main\zero123\gradio_new.py", line 24, in <module>
    from ldm.models.diffusion.ddim import DDIMSampler
  File "C:\transformers\stable-zero123\zero123-main\zero123\ldm\models\diffusion\ddim.py", line 9, in <module>
    from ldm.modules.diffusionmodules.util import make_ddim_sampling_parameters, make_ddim_timesteps, noise_like, extract_into_tensor
  File "C:\transformers\stable-zero123\zero123-main\zero123\ldm\modules\diffusionmodules\util.py", line 18, in <module>
    from ldm.util import instantiate_from_config
  File "C:\transformers\stable-zero123\zero123-main\zero123\ldm\util.py", line 17, in <module>
    import cv2
  File "C:\Users\user\anaconda3\envs\zero123\lib\site-packages\cv2\__init__.py", line 190, in <module>
    bootstrap()
  File "C:\Users\user\anaconda3\envs\zero123\lib\site-packages\cv2\__init__.py", line 184, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\user\anaconda3\envs\zero123\lib\site-packages\cv2\__init__.py", line 37, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\user\anaconda3\envs\zero123\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\user\anaconda3\envs\zero123\lib\site-packages\cv2\typing\__init__.py", line 169, in <module>
    LayerId = cv2.dnn.DictValue
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'

(zero123) C:\transformers\stable-zero123\zero123-main\zero123>

**Comment by zaiisao** [comment]
This was mentioned in another thread and a solution was presented: https://github.com/cvlab-columbia/zero123/issues/84#issuecomment-1685477425
The solution worked for me too.
