### ISSUE TITLE
Demo version is not working properly

### ISSUE THREAD

**Issue by 23hyun** [cvlab-columbia/zero123#84]
Runtime error is occurring When will it be restored?

**Comment by yuedajiong** [comment]
+1

**Comment by sidsunny** [comment]
@23hyun @yuedajiong I uninstalled opencv and installed it again using
`pip install opencv-python`
and it worked for me.

**Comment by alparius** [comment]
> @23hyun @yuedajiong I uninstalled opencv and installed it again using `pip install opencv-python` and it worked for me.

I beleive they are talking about this demo: https://huggingface.co/spaces/cvlab/zero123-live

**Comment by rheros** [comment]
I get a  way
reinstall opency-python
my old version is  4.5.5.64  
reInstall is  4.8.1.78

**Comment by ChlaegerIO** [comment]
I now get a numpy error instead and a numpy version warning as opencv-python has a newer numpy dependency, on windows:

C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 2.0.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "C:\Users\berno\Documents\Timo\3_Masterarbeit\zero123\zero123\gradio_new.py", line 7, in <module>
    import diffusers  # 0.12.1
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\diffusers\__init__.py", line 54, in <module>
    from .pipelines import (
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\diffusers\pipelines\__init__.py", line 18, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\diffusers\pipelines\dance_diffusion\__init__.py", line 2, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\diffusers\pipelines\dance_diffusion\pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 36, in <module>
    from ..schedulers.scheduling_utils import SCHEDULER_CONFIG_NAME
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\diffusers\schedulers\__init__.py", line 72, in <module>
    from .scheduling_lms_discrete import LMSDiscreteScheduler
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\diffusers\schedulers\scheduling_lms_discrete.py", line 21, in <module>
    from scipy import integrate
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\scipy\__init__.py", line 211, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "C:\Users\berno\miniconda3\envs\zero123\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\scipy\integrate\__init__.py", line 91, in <module>
    from ._quadrature import *
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\scipy\integrate\_quadrature.py", line 12, in <module>
    from scipy.special import roots_legendre
  File "C:\Users\berno\miniconda3\envs\zero123\lib\site-packages\scipy\special\__init__.py", line 649, in <module>
    from . import _ufuncs
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by ChlaegerIO** [comment]
I tried some combinations and it works now. I reinstalled the newest opencv-python, then I reinstalled scipy 1.9.1 which installs numpy 1.24.4. 
- opencv-python             4.10.0.84
- numpy                     1.24.4

The problem that I still have is #139, but I guess this is not related to this.
